Repository percona/mongodb_exporter, pull requests merged in 2021-11, with the labels that each got.

#374 Update issue templates and contribution guidelines
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: community

#351 Add docker image link to the Readme
  README.md
Labels: community, hacktoberfest-accepted

#371 README.md: Improve notes on the previous versions of the exporter
  README.md
Labels: enhancement, community, hacktoberfest-accepted
